version: '2.1'

services:
    Lara-nginx:
      container_name: Lara-nginx
      build:
        context: ./
        dockerfile: ./docker/nginx-docker/nginx-Dockerfile
      environment:
        TZ: America/Halifax
      ports:
        - "80:80"
      volumes:
        - ~/.lara/logs/nginx:/var/log/nginx
      depends_on:
        - Lara-backend
        - Lara-frontend


    Lara-mysql:
      container_name: Lara-mysql
    environment:
      TZ: America/Halifax

    Lara-backend:
      container_name: Lara-backend
      build:
        context: ./
        dockerfile: ./docker/server-docker/server-Dockerfile
      working_dir: /app
      environment:
        TZ: America/Halifax
      volumes:

      expose:
        - "8080"
      command: mvn spring-boot:run -Dmaven.test.skip=true
      depends_on:
        - Lara-mysql
      restart: always

    Lara-frontend:
      container_name: Lara-frontend
      build:
        context: ./
        dockerfile: ./docker/client-docker/client-Dockerfile
      environment:
        TZ: America/Halifax
      expose:
        - "3000"

